[package]
name = "ibkrust"
version = "0.1.0"
authors = ["Fletcher Haynes <fletcher@capitalprawn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "*"
anyhow = "*"
log = "0.4.11"
env_logger = "*"